export default {
  SAFE_AREA_BG: '#212f52',
  POKEMON_NAME: '#C30D13',
  PROGRESS_BAR: '#6690ff',
  YELLOW_POKEMON: '#fecc04',
  FONT_SIZE_EXTRA_SMALL: 9,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM_SMALL: 16,
  FONT_SIZE_MEDIUM__REGULAR: 22,
  FONT_SIZE_LARGE: 30,
  FONT_SIZE_EXTRA_LARGE: 36,
};
